apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: todo-api

resources:
  - deployment.yaml
  - service.yaml
  - secrets.yaml
  - postgres-deployment.yaml

commonLabels:
  app.kubernetes.io/name: todo-api
  app.kubernetes.io/component: api
  app.kubernetes.io/managed-by: kubectl
